ConstructionManagement/CMS.MVC/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.MVC.Models;

namespace CMS.MVC.Controllers
{
    public class AccountController:Controller
    {
        IAuthProvider authProvider;

        public AccountController(IAuthProvider auth)
        {
            authProvider = auth;
        }

        public ViewResult Login()
        {
            return View();

        }

        public ActionResult Logout()
        {
            string[] myCookies = Request.Cookies.AllKeys;
            foreach (string cookie in myCookies)
            {
                Response.Cookies[cookie].Expires = DateTime.Now.AddDays(-1);
            }
            return Redirect(Url.Action("Index", "Admin"));
        }
        [HttpPost]
        public ActionResult Login(LoginVM model, string returlUrl)
        {
            if (ModelState.IsValid)

            {
                try
                {
                    var role = authProvider.Authenticate(model.username, model.password);
                    if (role < 4 && role > 0)
                    {
                        ModelState.AddModelError("", "This user cannot access administrative options. Please contact your supervisor if this message is received in error.");
                        return View();

                    }
                    else if (role == 4)
                    {

                        return Redirect(returlUrl ?? Url.Action("Index", "Admin"));
                    }
                    else
                    {
                        ModelState.AddModelError("", "Incorrect username or password");
                        return View();
                    }
                }
                catch 
                {
                   
                    return View();
                }

            }
            else
            {
                return View();
            }
        }
    }

}

ConstructionManagement/CMS.MVC/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using Cms.DomainLogic;
using CMS.MVC.Helpers;
using CMS.MVC.Models;
using Newtonsoft.Json;

namespace CMS.MVC.Controllers
{
    public class userController : Controller
    {
        DomainLogic dl = new DomainLogic();
        // GET: user
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ActivateTask(int Id, int employeeId)
        {
            dl.UpdatePersonTask(dl.GetPersonTasks().First(e=>e.Id == Id), 6);
            return RedirectToAction("ListTasks",new {id = employeeId});
        }
        public ActionResult CompleteTask(int Id, int employeeId)
        {
          
           var x =  new TimeClock();
            x.CalculateTotals(dl.GetPersonTasks().First(e=>e.Id == Id));
            dl.UpdatePersonTask(dl.GetPersonTasks().First(e => e.Id == Id), 7);
            return RedirectToAction("ListTasks", new { id = employeeId });
        }

        public ActionResult ListTasks(int id)
        {
            ViewBag.Statuses = dl.GetStatuses();
            ViewBag.Employee = dl.GetEmployees().First(e => e.ID == id);
            var temp = dl.GetPersonTasks().ToViewModel().Where(p => p.EmployeeId == id);
            if (temp.Any())
                return View(temp);
            else
            {
                TempData["TaskEmpty"] = true;
            return RedirectToAction("Clock", new {id = id});
             }
    }

        public ActionResult EnterUsername()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EnterUsername(DetailMV d)
        {
            try
            {
               var details = dl.GetDetails().First(m => m.username.ToLower() == d.username.ToLower());
                var person = dl.GetEmployees().First(e => e.DetailID == details.ID);
                return RedirectToAction("ListTasks",new {id=person.ID});
            }
            catch (Exception)
            {
                ModelState.AddModelError("","User cannot be found");
                return View();
            }
        }

        public ActionResult Clock(int id)
        {
            var tc = new TimeClock();
            tc.Clock(dl.GetEmployees().First(e => e.ID == id));
            var HasTask = dl.GetPersonTasks().Any(e => e.EmployeeId == id);
            if (dl.GetPersonTasks().Any(e => e.EmployeeId == id))
                return RedirectToAction("ListTasks", new {id = id});
            else
            {
                if (!dl.GetPersonTasks().Any(e => e.EmployeeId == id))
                {
                    var temp = dl.GetEmployees().First(e => e.ID == id).ClockedOut;
                    if (!temp)
                    {
                        TempData["Message"] = "You have been clocked in! But you don't have any assigned tasks! Contact your manager.";
                    }
                    else
                    {
                        TempData["Message"] = "You have been clocked out!";
                    }

                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("ListTasks", new { id = id });

        }
        public ActionResult JsonString()
        {
            var mytemp = dl.GetWorkDays().GroupBy(x => new {x.DateModified.Value.Date, x.EmployeeId}).Distinct();
            var temp = dl.GetWorkDays().GroupBy(e => e.DateModified.Value.Date).Distinct();
            
            var dateList = new List<DateCount>();

            foreach (var item in mytemp)
            {
                dateList.Add(new DateCount()
                {
                    Count = item.Count(),
                    Date = item.First().DateModified.Value.Date.ToString("d")

                });
            }
            var dateList2 = new List<DateCount>();
            foreach (var item in dateList.GroupBy(e => e.Date))
            {
                dateList2.Add(new DateCount()
                {
                    Date = item.First().Date,
                    Count = item.Count()
                });;
            }

            var Json = JsonConvert.SerializeObject(dateList2.Skip(dateList2.Count - 7));
            return Content(Json, "application/json");
        }
    }
}

ConstructionManagement/CMS.MVC/Views/Shared/_Account.cshtml
@{
    ViewBag.Title = "Log in";
    Layout = "_Layout.cshtml";
}


@section Title
{
    @Html.ActionLink("Return to Employee Portal", "Index","user", new { area = "" }, new { @class = "navbar-brand" });
}


@RenderBody();
@section Scripts
{
    @RenderSection("Scripts", false)
}

ConstructionManagement/CMS.MVC/Views/Shared/_Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "_Layout.cshtml";
}


@section Title
{
    @Html.ActionLink("Management Portal", "Index","Admin", new { area = "" }, new { @class = "navbar-brand" });
}

@section NavBar
{<li>@Html.ActionLink("View Employees", "ListEmployees", "Admin")</li>

}
@section RightSide
{
    <button style="margin-top:5px" class='btn btn-secondary pull-right' onclick="window.location.href='@Url.Action("Logout","Account")'" >Log Out</button>
}
@RenderBody();
@section Scripts
{
    @RenderSection("Scripts", false)
}

ConstructionManagement/CMS.MVC/Views/Shared/_Employee.cshtml
@{
    ViewBag.Title = "Employee";
    Layout = "_Layout.cshtml";
}


@section Title
{
    @Html.ActionLink("Employee Portal", "Index","user", new { area = "" }, new { @class = "navbar-brand" });
}
@section RightSide
{
    <button style="margin-top:5px" class='btn btn-secondary pull-right' onclick="window.location.href='@Url.Action("Index","Admin")'">Managment</button>
}
@section NavBar
{<li>@Html.ActionLink("Time Clock", "EnterUsername", "user")</li>

}

@RenderBody();
@section Scripts
{

    @RenderSection("Scripts", false)
}

ConstructionManagement/CMS.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
           @RenderSection("Title",false);
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @RenderSection("NavBar", false);
            </ul>
            @RenderSection("RightSide",false);
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - By Alex Redmon</p>
    </footer>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
@RenderSection("Scripts", false)
<script>
    function AddErrorMessage(target,message) {
        $('#' + target).append('<li>' + message + '</li>');
        $('#' + target).css('color', 'red');
    }
    function ErrorColor(selector) {
        $('#' + selector).css('background-color', '#FA8072');
    }
</script>
</body>
</html>